### ISSUE TITLE
Implementing gamma

### ISSUE THREAD

**Issue by particlerain** [hpwit/artnetESP32#12]
Hi hpwit,

I use gamma in my fastled codes and would like to implement it to your code too. Unfortunately your code have so many read buffers, i could not see where i can insert the small code for the gamma lookup table..

I nıormally do it like below with fastled:

` byte r = pgm_read_byte(&gamma8[data[i * 3]]); 
      byte g = pgm_read_byte(&gamma8[data[i * 3 + 1]]); 
      byte b = pgm_read_byte(&gamma8[data[i * 3 + 2]]);  
      leds[led] = CRGB(r, g, b);
`

So where in your artnetESP32.cpp file can i insert my gamma lookup code?

Thanks for your advice.

**Comment by hpwit** [comment]
Hello
@particlerain  you would like to implement the gamma when storing the artnet buffers ?
It’s gonna be way to slow. The gamma correction should take place in the display driver. I don’t remember if fastLED can donthis but my i2sclocklesslibrary can do it

**Comment by hpwit** [comment]
hello
The clockless library is compatible with the artnet library you're using.
you just replace Fastled.show() by driver.show() and the library as the
tool to define gamma for each colour.
The esp32 is really slow at reading memory especially for a look up table.
if you link me to your code I will make the necessary adjustements

regards


Le mar. 20 juin 2023 à 21:35, particlerain ***@***.***> a
écrit :

**Comment by hpwit** [comment]
hello
here is the code
```C
#include <Arduino.h>
#include <WiFi.h>
#define FASTLED_ESP32_I2S true
#include <FastLED.h>

#define NUM_LEDS_PER_STRIP 170
#define NUMSTRIPS 6
#define NUM_PIXELS NUM_LEDS_PER_STRIP * NUMSTRIPS
#define numLeds NUM_PIXELS

#define UNIVERSE_SIZE 170
#define START_UNIVERSE 0


CRGB leds[numLeds]; // 6 Universes * 170px = 1020 leds
#include <ArtnetESP32.h>
#include "I2SClocklessLedDriver.h"
ArtnetESP32 artnet;
I2SClocklessLedDriver driver;

int pins[NUMSTRIPS]={15,2,0,4,16,33};
char *ssid="ssid";
char *pass="pass";
void displayfunction()
{
if (artnet.frameslues%100==0)
Serial.printf("nb frames read: %d nb of incomplete frames:%d lost:%.2f %%\n"
,artnet.frameslues,artnet.lostframes,(float)(artnet.lostframes*100)/artnet.
frameslues);
//here the buffer is the led array hence a simple FastLED.show() is enough
to display the array
driver.showPixels();
}

void setup() {
Serial.begin(115200);
delay(1000); // for fastled

WiFi.mode(WIFI_STA);
WiFi.disconnect();
delay(100);
WiFi.begin(ssid,pass);
/*
FastLED.addLeds<WS2812B, 15, GRB>(leds, 0,NUM_LEDS_PER_STRIP);
FastLED.addLeds<WS2812B, 2, GRB>(leds,
1NUM_LEDS_PER_STRIP,NUM_LEDS_PER_STRIP);
FastLED.addLeds<WS2812B, 0, GRB>(leds,
2NUM_LEDS_PER_STRIP,NUM_LEDS_PER_STRIP);
FastLED.addLeds<WS2812B, 4, GRB>(leds,
3NUM_LEDS_PER_STRIP,NUM_LEDS_PER_STRIP);
FastLED.addLeds<WS2812B, 16, GRB>(leds,
4NUM_LEDS_PER_STRIP,NUM_LEDS_PER_STRIP);
FastLED.addLeds<WS2812B, 33, GRB>(leds,
5*NUM_LEDS_PER_STRIP,NUM_LEDS_PER_STRIP);
*/
driver.initled((uint8_t*)leds,pins,NUMSTRIPS,NUM_LEDS_PER_STRIP,ORDER_GRB);
// driver.setBrightness(200);
driver.setGamma(2.8,2.8,2.8); //you can set the GAMMA Value for each
channel red,green,blue
artnet.setFrameCallback(&displayfunction); //set the function that will be
called back a frame has been received
artnet.setLedsBuffer((uint8_t*)leds); //set the buffer to put the frame
once a frame has been received
artnet.begin(NUM_PIXELS,UNIVERSE_SIZE, START_UNIVERSE); //configure artnet
}

void loop() {
artnet.readFrame();
}
```

you'll need this library https://github.com/hpwit/I2SClocklessLedDriver
let me know
regards
Yves

Le jeu. 22 juin 2023 à 18:43, particlerain ***@***.***> a
écrit :

**Comment by hpwit** [comment]
HelloI can invert the gamma in the calculation. That is no issue Can you send me your full code I don’t get why the test led is not working RegardsYves On 22 Jun 2023, at 23:47, particlerain ***@***.***> wrote:﻿
Another issue is:
i can not init test the leds. Leds get not initialized  with the  initTest(); command in setup. Whether its before or after artnet begin
With your previous esp32artnet code they get initialized , but not with clockless driver. :(
    driver.setGamma(0.4,0.4,0.4); //you can set the GAMMA Value for each channel red,green,blue
    initTest();
    artnet.setFrameCallback(&displayfunction); //set the function that will be called back a frame has been received
    artnet.setLedsBuffer((uint8_t*)leds); //set the buffer to put the frame once a frame has been received
    artnet.begin(NUM_LEDS,UNIVERSE_SIZE, START_UNIVERSE); //configure artnet

void initTest()
{
  for (int i = 0 ; i < numLeds ; i++)
    leds[i] = CRGB( 50, 0, 0);
  driver.showPixels();
  delay(150);
  for (int i = 0 ; i < numLeds ; i++)
     leds[i] = CRGB( 0, 50, 0);
  driver.showPixels();
  delay(150);
  for (int i = 0 ; i < numLeds ; i++)
   leds[i] = CRGB( 0, 0, 50);
  driver.showPixels();
  delay(150);
  for (int i = 0 ; i < numLeds ; i++)
    leds[i] = CRGB( 0, 0, 0);
  driver.showPixels();
}

**Comment by hpwit** [comment]
Hello
in the I2SClocklessdriver.h
change
 void setBrightness(int brightness)
    {
        _brightness = brightness;
        float tmp;
        for (int i = 0; i < 256; i++)
        {
            tmp = powf((float)i / 255, 1 / _gammag);
            __green_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255, 1 / _gammag);
            __blue_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255, 1 / _gammag);
            __red_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255, 1 / _gammag);
            __white_map[i] = (uint8_t)(tmp * brightness);
        }
    }


to

 void setBrightness(int brightness)
    {
        _brightness = brightness;
        float tmp;
        for (int i = 0; i < 256; i++)
        {
            tmp = powf((float)i / 255, _gammag);
            __green_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255,  _gammag);
            __blue_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255,  _gammag);
            __red_map[i] = (uint8_t)(tmp * brightness);
            tmp = powf((float)i / 255, _gammag);
            __white_map[i] = (uint8_t)(tmp * brightness);
        }
    }

Le ven. 23 juin 2023 à 13:37, particlerain ***@***.***> a
écrit :

**Comment by hpwit** [comment]
HelloThank you !! Can you share a video of your build?I also have the new version of the artnet library ArtnetESP32V2 Yves On 24 Jun 2023, at 11:16, particlerain ***@***.***> wrote:﻿
Thanks @hpwit . Everything is fine now. Thanks for this great library.
