### ISSUE TITLE
artnet.setLedsBuffer((uint8_t*)T8Leds); problem concept

### ISSUE THREAD

**Issue by gabyleon** [hpwit/artnetESP32#4]
i´ve 24 universes (150 ws2812b leds each) attached to 8 pins in my ESP32.
I´ve problems with artnet.setLedsBuffer. In the example provided, i understand than you put the buffer to one pin. 
----------------------------------
Part of mi code is here:
-defines numleds, universes, etc....

CRGB T1Leds[NUM_LEDS_PER_STRIP];
CRGB T2Leds[NUM_LEDS_PER_STRIP];
(until T8Leds)
......
  FastLED.addLeds<NEOPIXEL, 12>(T1Leds, NUM_LEDS_PER_STRIP);
  FastLED.addLeds<NEOPIXEL, 13>(T2Leds, NUM_LEDS_PER_STRIP);
(until T8Leds, too).
......

 artnet.setFrameCallback(&displayfunction); 
artnet.setLedsBuffer((uint8_t*)**<what?>**); //set the buffer to put the frame once a frame has been received
 artnet.begin(NUM_LEDS,UNIVERSE_SIZE); 

How can I use artnet.setLedsBuffer with multiple pins?

Thanks in advance.
* edit i'm looking you code....and perhaps this parameter is the total numer of leds? ( in this case, 24*150)?

**Comment by hpwit** [comment]
There is no link between the number of pins and the number of universes
to respect your code
in that case you need to do this

CRGB alleds[NUM_LEDS_PER_STRIP*8]; 
CRGB * T1Leds=allleds;
CRGB  *T2Leds=&allleds[NUM_LED_PER_STRIP];
CRGB  *T3Leds=&allleds[2*NUM_LED_PER_STRIP];
...
CRGB  *T8Leds=&allleds[7*NUM_LED_PER_STRIP];

FastLED.addLeds<NEOPIXEL, 12>(T1Leds, NUM_LEDS_PER_STRIP);
FastLED.addLeds<NEOPIXEL, 13>(T2Leds, NUM_LEDS_PER_STRIP);

artnet.setLedsBuffer((uint8_t*)alleds);

//yes NUM_LEDS is 24*150 which is 8*450 I guess you have 450 leds per strip

let me know

**Comment by hpwit** [comment]
Hello
did it solve you issue ?
rgds
Yves
