### ISSUE TITLE
merge virtual led driver with artnet ,any exception?

### ISSUE THREAD

**Issue by ScobbyDoo** [hpwit/artnetESP32#5]
Is it possible to play with virtual driver with streaming artnet data around 64 output pins & each pins have 100 or 200 leds?

Total Raw data approximately 

         200.00 led per line
         64.00  line means  **12,800.00**  total led

      
       Into 3.00 byte(RGB) ~ 38,400.00  Total size 
 
       

Total buffer size without artnet's header data & other operation 

Is it technically possible to even think about to make it possible? ( I don't have much experience about calculation fot this kind of setup 😅)

**Comment by hpwit** [comment]
Hello
Yes it’s possible. I use it on my panel. But 12800 leds this is 76 universes so in term of timing via wifi I don’t know if it will work.
