### ISSUE TITLE
readSD : "available" command seems not work

### ISSUE THREAD

**Issue by derrgis** [hpwit/artnetESP32#6]
While some artnet examples work this is not the case for the readSD.ino 
For now I'm not able to light up my leds from the SD, it sounds like FastLED.show() does nothing

We tryed to debug :
myFile.available return 0 however it seems possible to print the artnet values from the SD to the console
sounds like a non-sense ...

//-------------------------- ici on a tenté avec Yves de tester le fichier-----------------
  myFile=SD.open("/artnetRecorded.txt"); //ouvrir et écrire dans ce fichier

    // on comprend pas pourquoi myFile.available retourne 0 alors qu'on arrive à afficher les valeurs de la SD
    uint8_t r[170];
    myFile.read(r,170);

    for(int l=0; l<170; l++){
    Serial.print(r[l]); //afficher 170 valeurs artnet écrites sur le fichier de la SD (ça marche)
    }
    
     Serial.println("testSD_start");
      myFile.seek(0);//revenir au début du fichier
    Serial.println(myFile.available());//retourne 1 ou 0 pour indiquer si le fichier fonctionne
      Serial.println("testSD_end");
//-------------------------------------------------------------------------------------------

// SORTIE 
12:09:44.718 -> WiFi connected.
12:09:44.718 -> IP address: 
12:09:44.718 -> 192.168.0.38
12:09:44.765 -> 16516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516516521683864228152864480500000240312516300000000000000001809613640000000000000000000000000000000000000000000000000000
12:09:44.765 -> testSD_start
12:09:44.765 -> 0
12:09:44.765 -> testSD_end
12:09:44.765 -> Starting artnet with starting universe :0
12:09:44.765 -> Starting Artnet nbNee sdedUniverses:1
12:09:44.765 -> Reading done nbframes:0 totlrecord 0 ms
12:09:44.765 -> Reading done nbframes:0 totlrecord 0 ms
12:09:44.812 -> Reading done nbframes:0 totlrecord 0 ms
12:09:44.812 -> Reading done nbframes:0 totlrecord 0 ms
.
.
.
.

**Comment by hpwit** [comment]
hello 
could you replace
```c
    if (playingfile.available() > 0)
    {
        uint32_t waitnewtframe = 0;
        playingfile.read(getframeread(buffer_read), nbPixels * 3 + 4);
```

by
```c
   size_t s=playingfile.read(getframeread(buffer_read), nbPixels * 3 + 4);
    if (s > 0)
    {
        uint32_t waitnewtframe = 0;
       
```
